#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include <nativeStuff.h> // generated by javah via maven-native-plugin

ARDiscovery_Device_t *device = NULL;
ARCONTROLLER_Device_t *deviceController = NULL;

JNIEXPORT void JNICALL Java_com_inocybe_parrot_Drone_connect 
   (JNIEnv * env, jobject obj)
 {
    eARDISCOVERY_ERROR errorDiscovery = ARDISCOVERY_OK;
    ARDiscovery_Device_t *device = NULL;
    const char *ip = "192.168.42.1"
    
    if (ip == NULL || port == 0)
    {
        fprintf(stderr, "Bad parameters");
        return device;
    }
    if (product < ARDISCOVERY_PRODUCT_NSNETSERVICE || product >= ARDISCOVERY_PRODUCT_BLESERVICE)
    {
        fprintf(stderr, "Bad product (not a wifi product)");
        return device;
    }

    device = ARDISCOVERY_Device_New(&errorDiscovery);

    if (errorDiscovery == ARDISCOVERY_OK)
    {
        errorDiscovery = ARDISCOVERY_Device_InitWifi (device, product, name, port);
    }

    if (errorDiscovery != ARDISCOVERY_OK)
    {
        ARDISCOVERY_Device_Delete(&device);
    }

eARCONTROLLER_ERROR error = ARCONTROLLER_OK;
ARCONTROLLER_Device_t *deviceController = ARCONTROLLER_Device_New (discoveryDevice, &error);
}


JNIEXPORT void JNICALL Java_com_inocybe_parrot_Drone_takeoff
  (JNIEnv * env, jobject obj)
{
    if (deviceController == NULL)
    {
        return;
    }
    if (getFlyingState(deviceController) == ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_LANDED)
    {
        deviceController->aRDrone3->sendPilotingTakeOff(deviceController->aRDrone3);
    }
}


JNIEXPORT void JNICALL Java_com_inocybe_parrot_Drone_land
  (JNIEnv * env, jobject obj)
{
  if (deviceController == NULL)
    {
        return;
    }
    eARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE flyingState = getFlyingState(deviceController);
    if (flyingState == ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_FLYING || flyingState == ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_HOVERING)
    {
        deviceController->aRDrone3->sendPilotingLanding(deviceController->aRDrone3);
    }
}

JNIEXPORT void JNICALL Java_com_inocybe_parrot_Drone_pilot
  (JNIEnv * env, jobject obj, jinti pitch, jint yaw, jint roll, jint gaz)
{
deviceController->aRDrone3->setPilotingPCMDFlag(deviceController->aRDrone3, 1);
deviceController->aRDrone3->setPilotingPCMDPitch(deviceController->aRDrone3, pitch);
deviceController->aRDrone3->setPilotingPCMDYaw(deviceController->aRDrone3, yaw);
deviceController->aRDrone3->setPilotingPCMDRoll(deviceController->aRDrone3, roll);
deviceController->aRDrone3->setPilotingPCMDGaz(deviceController->aRDrone3, gaz);
}
